name: Upload Build

on:
  workflow_dispatch:

jobs:
  upload-build:
    runs-on: macos-15
    timeout-minutes: 720
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Install deps
        run: |
          brew install ninja lld llvm meson
          bundle install
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Fastlane
        timeout-minutes: 720
        run: script fastlane.log bundle exec fastlane upload_build
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - uses: actions/upload-artifact@v4
        with:
          name: App
          path: |
            iSH.ipa
            iSH.app.dSYM.zip

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Fastlane Logs
          path: |
            fastlane.log
            ~/Library/Logs/gym

